### ISSUE TITLE
include ipv6 functionality

### ISSUE THREAD

**Issue by dvandok** [salt-formulas/salt-formula-iptables#2]
Hi,

as a feature request, I would like to see IPv6 support for this formula.

Cheers,

Dennis

**Comment by fpytloun** [comment]
I agree, that would be good and I don't think it's difficult to implement - if there will be no volunteers to add this support, I'll do this in my spare time :-)

**Comment by dvandok** [comment]
Great! I was going to give it a go, but there is probably more then one way to go about it. Maybe we should have a short discussion on which approach to take.

I already wrote a bcp.sls to reflect 'best current practices' for the kinds of icmp requests to generally let through for both ipv4 and ipv6; for ipv6 this is actually necessary for the proper functioning of the protocol.
https://gist.github.com/dvandok/d7aebe3f03061169606f754271d2a757

**Comment by dvandok** [comment]
Looking at the structure I'm now leaning towards having the 'family' choice as part of each rule. It makes for more logical grouping of rules. I see that the standard chain names are the same for ipv4 and ipv6.

**Comment by dvandok** [comment]
This was easy. See pull request #3
